#ifndef COLORS_H
#define COLORS_H

#include <stdint.h>

#include "constants.h"

inline uint32_t red(uint8_t x) {
    return (((uint32_t)x) << 8);
}

inline uint32_t grn(uint8_t x) {
    return (((uint32_t)x) << 0);
}

inline uint32_t blu(uint8_t x) {
    return (((uint32_t)x) << 16);
}

inline uint32_t wht(uint8_t x) {
    return (((uint32_t)x) << 24);
}

#define OFF 0
#define RED 1
#define GRN 2
#define BLU 3
#define WHT 4
#define YLW 5

static uint32_t colors[256] = {
    0,                                 // off
    red(BRIGHTNESS),                   // red
    grn(BRIGHTNESS),                   // green
    blu(BRIGHTNESS),                   // blue
    wht(BRIGHTNESS),                   // white
    red(BRIGHTNESS) + grn(BRIGHTNESS), // yellow
};

#define INIT_STEPS 100
static uint8_t init_sequence_tach[INIT_STEPS][16] = {
    {WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, OFF},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, GRN, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, GRN, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, GRN, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED},
    {WHT, WHT, GRN, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF, RED, RED}};

#endif // COLORS_H
