#ifndef CONSTANTS_H
#define CONSTANTS_H

#define BRIGHTNESS 16

#define COOLANT 0
#define STATUS_BARS 1
#define SHIFT_LIGHTS 2
#define TACHOMETER 3

#define STARTER 0
#define DEBUG_ACTIVE 1
#define DEBUG_CONTROL 2

#define STATE_IDLE 0
#define STATE_INIT 1
#define STATE_NORMAL 2
#define STATE_DEBUG 3

#define ENTER_IDLE_CYCLES 100
#define ENTER_DEBUG_CYCLES 100

#define CEL_CODES 48

#endif // CONSTANTS_H
